// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendDbContext))]
    partial class BackendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Ecologica")
                        .HasColumnType("bit");

                    b.Property<string>("Localizacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Bodegas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Ecologica = true,
                            Localizacion = "Toledo",
                            Nombre = "Lavero"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Ecologica = false,
                            Localizacion = "Rioja",
                            Nombre = "CincoVillas"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Ecologica = true,
                            Localizacion = "Zaragoza",
                            Nombre = "Zierzo"
                        });
                });

            modelBuilder.Entity("Backend.Models.Vino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Año")
                        .HasColumnType("datetime2");

                    b.Property<int>("BodegaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Graduacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreBodega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vinos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Año = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BodegaId = 2,
                            Graduacion = 15.5m,
                            Nombre = "Ramon Bilbo",
                            NombreBodega = "CincoVillas",
                            Precio = 10.5f,
                            Stock = 100,
                            Tipo = "Tinto"
                        },
                        new
                        {
                            Id = 2,
                            Año = new DateTime(2018, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BodegaId = 1,
                            Graduacion = 10.5m,
                            Nombre = "Rosetti",
                            NombreBodega = "Lavero",
                            Precio = 17.5f,
                            Stock = 50,
                            Tipo = "Rosado"
                        },
                        new
                        {
                            Id = 3,
                            Año = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BodegaId = 3,
                            Graduacion = 9.5m,
                            Nombre = "Nieves",
                            NombreBodega = "Zierzo",
                            Precio = 11.2f,
                            Stock = 80,
                            Tipo = "Blanco"
                        },
                        new
                        {
                            Id = 4,
                            Año = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BodegaId = 1,
                            Graduacion = 8.5m,
                            Nombre = "Swarser",
                            NombreBodega = "Lavero",
                            Precio = 5.5f,
                            Stock = 150,
                            Tipo = "Espumoso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
